/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import io.socket.client.IO;
import io.socket.client.Socket;
import io.socket.emitter.Emitter;
import java.awt.Color;
import javax.swing.JOptionPane;




/**
 *
 * @author Jade González
 */
public class Chat extends javax.swing.JFrame {

    /**
     * Creates new form Chat
     */
    public Chat() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
  
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        lblStado = new javax.swing.JLabel();
        btnConnect = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SMS = new javax.swing.JTextArea();
        btnSent = new javax.swing.JButton();
        txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setBackground(new java.awt.Color(226, 226, 226));
        name.setBorder(null);
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 350, 30));

        lblStado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblStado.setForeground(new java.awt.Color(255, 0, 0));
        lblStado.setText("Offline");
        jPanel1.add(lblStado, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        btnConnect.setText("Conectar");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });
        jPanel1.add(btnConnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 106, -1));

        SMS.setEditable(false);
        SMS.setColumns(20);
        SMS.setRows(5);
        jScrollPane1.setViewportView(SMS);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 510, 290));

        btnSent.setText("Enviar");
        btnSent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSentActionPerformed(evt);
            }
        });
        jPanel1.add(btnSent, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 110, 30));

        txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActionPerformed(evt);
            }
        });
        jPanel1.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 310, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Downloads\\Rectangle 45.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Downloads\\8c98994518b575bfd8c949e91d20548b.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private Socket s;
private String UserName;


    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
      if (name.getText().isEmpty()){
      JOptionPane.showMessageDialog(null, "Tiene que añadir su nombre de usuario");
      } else {
        
        try {
       UserName = name.getText().trim();
      s= IO.socket("http://localhost:3000");
      s.on(Socket.EVENT_CONNECT, new Emitter.Listener(){
           @Override
           public void call(Object... os) {
               lblStado.setText("Online");
               lblStado.setForeground(new Color(22, 139, 47));
               
           }
          
      });
        
         s.on(Socket.EVENT_DISCONNECT, new Emitter.Listener() {
           @Override
           public void call(Object... os) {
            lblStado.setText("Offline");
               lblStado.setForeground(new Color(196, 57, 57));  
           }
         });
         s.on("message", new Emitter.Listener() {
           @Override
           public void call(Object... arg0) {
              SMS.append(arg0[0].toString()+ "\n");
           }
         });
         
         s.open();
         
        }catch(Exception e){
            e.printStackTrace();
        }
      }
        
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnSentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSentActionPerformed

        if (txt.getText().isEmpty()){
     JOptionPane.showMessageDialog(null, "No puede dejar la bandeja sin un mensaje");
      }else{
            

        s.emit("message", UserName+" : "+ txt.getText().trim());
      txt.setText("");
      txt.grabFocus();
      }
        
     
    }//GEN-LAST:event_btnSentActionPerformed

    private void txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActionPerformed





    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea SMS;
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnSent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStado;
    private javax.swing.JTextField name;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables
}
